# Generated by Django 3.2.18 on 2023-05-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.DateTimeField(choices=[('9 AM - 10 AM', '9 AM - 10 AM'), ('11 - 12 AM', '11 - 12 AM'), ('16 PM - 17 PM', '16 PM - 17 PM')]),
        ),
    ]
