# Generated by Django 3.2.18 on 2023-05-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('9:00 - 10:00 AM', '9:00 - 10:00 AM'), ('11 - 12 AM', '11 - 12 AM'), ('16 PM - 17 PM', '16 PM - 17 PM')], max_length=32),
        ),
    ]
