# Generated by Django 3.2.18 on 2023-05-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_alter_booking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('9:00 - 10:00 AM', '9:00 - 10:00 AM'), ('11:00 - 12:00 AM', '11:00 - 12:00 AM'), ('16:30 PM - 17:30 PM', '16:30 PM - 17:30 PM')], max_length=32),
        ),
    ]
