# Generated by Django 3.2.19 on 2023-06-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0007_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Form Submission'},
        ),
    ]
