# Generated by Django 3.2.18 on 2023-05-23 14:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.IntegerField(choices=[(9, '9:00 - 10:00 AM'), (11, '11:00 - 12:00 AM'), (16, '16:30 PM - 17:30 PM')], default=9),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, related_name='hiuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
