# Generated by Django 3.2.18 on 2023-06-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20230531_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.IntegerField(choices=[(9, '9:00 - 10:00 AM'), (11, '11:00 - 12:00 AM'), (16, '16:30 PM - 17:30 PM')], default=9),
        ),
    ]
