# Generated by Django 3.2.18 on 2023-05-16 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20230516_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekday',
            name='user',
        ),
        migrations.DeleteModel(
            name='AvailableHour',
        ),
        migrations.DeleteModel(
            name='WeekDay',
        ),
    ]
