# Generated by Django 3.2.18 on 2023-05-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20230516_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.IntegerField(choices=[(9, '9:00 - 10:00 AM'), (11, '11:00 - 12:00 AM'), (16, '16:30 PM - 17:30 PM')], default=9),
        ),
    ]
